### ISSUE TITLE
are there different sources fro cwr.js other than us-east-1? 

### ISSUE THREAD

**Issue by sebsonjura** [aws-observability/aws-rum-web#118]
We are aplanning to use rum in eu-central-1 and for a complete GDPR compatble usage I need to get the js file eiter: 

***from a domain that is under our control (and in eu-central-1)***
or 

*** or a AWS source in eu-central-1***

I did try to change the url from 'https://client.rum.us-east-1.amazonaws.com/1.0.2/cwr.js' to 'https://client.rum.eu-central-1.amazonaws.com/1.0.2/cwr.js'  and got a 404

any ideas?

**Comment by qhanam** [comment]
`cwr.js` is a globally distributed static resource. In this case, while the domain includes `us-east-1`, it will not necessarily be served from `us-east-1`. The inclusion of `us-east-1` to the domain name indeed does not follow AWS convention for globally distributed resources, and we are working on renaming the domain to `client.rum.amazonaws.com`.

Because `cwr.js` is a static file, it does not impact to which region data is sent (I believe this is your concern with GDPR). The (AppMonitor) region is configured by the application in the code snippet which installs the web client.

Also consider either (1) using the [NPM package](https://www.npmjs.com/package/aws-rum-web), (2) self-hosting or (3) building from source.
