### ISSUE TITLE
"CWR: Failed to retrieve Cognito identity" error thrown by aws-rum-web

### ISSUE THREAD

**Issue by tlakomy** [aws-observability/aws-rum-web#227]
Hello,

First of all - thank you for building CloudWatch RUM, looking forward to seeing how this project will evolve.

We just noticed a following issue in our DataDog (occurred only once so far):
<img width="1220" alt="Screenshot 2022-09-14 at 11 59 55" src="https://user-images.githubusercontent.com/16646517/190124405-73c28941-ae65-44d7-a0fb-08e3656b80cc.png">

Are there any actions we could take in order to avoid this error? Moreover, would it be possible to include the actual exception being thrown along with the `Failed to retrieve Cognito identity` error message?

**Comment by qhanam** [comment]
> would it be possible to include the actual exception being thrown along with the Failed to retrieve Cognito identity error message?

Yes I think this is a good suggestion. We'll pick it up.

> Are there any actions we could take in order to avoid this error?

If it's not consistently failing then I don't currently have any insight into what the root cause could be.

Have you been able to reproduce the error? If not, I agree that improving the error message is a good first step.

To minimize the bundle size, the rum-web-client doesn't use the complete AWS SDK to connect to Cognito or STS, so there could be edge cases that aren't handled. That's just speculation on my part though.

**Comment by qhanam** [comment]
There are two root causes of Cognito/STS failures outlined in the [troubleshooting doc](https://github.com/aws-observability/aws-rum-web/blob/main/docs/cdn_troubleshooting.md#aws-token-vending-cognito-or-sts-fails), however, I would expect Cognito/STS to be consistently failing in these cases.

**Comment by tlakomy** [comment]
@qhanam for the record - we're seeing those errors once every few days so it's not consistent

**Comment by qhanam** [comment]
Good to know; thanks!
