### ISSUE TITLE
[Feature Request]: Only add XRayTraceIdHeader to provided domains

### ISSUE THREAD

**Issue by rleij** [aws-observability/aws-rum-web#429]
### Please provide your feature request

We are trying to make use of the XRayTraceIdHeader but some of our requests to external servers are being blocked because of the header, which is to be expected.

Would be great if we could provide a list via the HttpPluginConfig with domains to which the XRayTraceIdHeader should be added, so it only adds the header when requests are being made to endpoints (our api's) which are known to allow the header.

We've worked around it for now by not adding 'http' to the telemetries and creating a custom HttpPlugin and XhrPlugin with this functionality, but for maintainability it would be great if the rum library would support such functionality.

**Comment by qhanam** [comment]
This is an interesting, thanks for opening this conversation!

Could we link this behavior to the existing [urlsToInclude/urlsToExclude](https://github.com/aws-observability/aws-rum-web/blob/main/docs/configuration.md#http) config options, or would we need a new config option? I imagine the set of requests one would want to trace would typically be a subset of the set of requests one would want to record. That would suggest we need a new config option (e.g., `urlsToTrace`).

We could also explore adding trace headers by default for same-origin requests, so that tracing is more likely to work without any additional configuration (i.e., "out of the box").

**Comment by rleij** [comment]
> Could we link this behavior to the existing [urlsToInclude/urlsToExclude](https://github.com/aws-observability/aws-rum-web/blob/main/docs/configuration.md#http) config options, or would we need a new config option? I imagine the set of requests one would want to trace would typically be a subset of the set of requests one would want to record. 

The [urlsToInclude/urlsToExclude](https://github.com/aws-observability/aws-rum-web/blob/main/docs/configuration.md#http) config options seem to serve a different purpose in which they can disable the tracing in as a whole so a new config option sounds like the way to go.

> That would suggest we need a new config option (e.g., `urlsToTrace`).

We used 'urlsToTraceWithXRayHeader'. Using 'urlsToTrace' would also be fine but sounds a little misleading as tracing would still work even if a url is not included in the 'urlsToTrace' config option, it would just not add the xray header id to the request.

> We could also explore adding trace headers by default for same-origin requests, so that tracing is more likely to work without any additional configuration (i.e., "out of the box").

This might work in some cases but in our case we always host the backend API under a subdomain, causing the requests to not be same-origin requests. For example an angular app is hosted on: 'https://www.xyz.com' and the api for the app uses: 'https://api.xyz.com'.

**Comment by qhanam** [comment]
This will be resolved by #466.

**Comment by spacebinn** [comment]
Thanks guys, looking forward to the next release!
