### ISSUE TITLE
[General Inquiry]: is unauthenticated user pool secure ?

### ISSUE THREAD

**Issue by ShawneeY** [aws-observability/aws-rum-web#488]
### What is your general inquiry?

AWS CloudWatch RUM leverages AWS Congnito and uses an unauthenticated indentity to "PutRumEvents". 

Does it mean that an malicious user of my web application can pretend to be the unauthenticated indentity to assume the IAM role and start abuse the "PutRumEvents" API thus pollute the frontend_logs or metrics collected by RUM ?

Many thanks in advance

**Comment by adebayor123** [comment]
1. We have throttling on the backend service to prevent an abnormal amount of incoming data (this handles the traffic spamming)
2. We have event schema based validation on the incoming RUM events. As a result, the spammers will have to still create data that follow the predefined event schemas. However, they can still create some arbitrary numbers to send inaccurate data.

That being said, due to the nature of Cognito, we cannot fully prevent a malicious user from spamming data.

**Comment by qhanam** [comment]
> an malicious user of my web application can pretend to be the unauthenticated indentity to assume the IAM role and start abuse the "PutRumEvents" API thus pollute the frontend_logs or metrics collected by RUM ?

This is an inherent risk of real user monitoring. The risk of receiving spoofed data may be increased when collecting data from unauthenticated users, but the risk is present even when collecting data from authenticated users. I wrote a blog post titled ["How to isolate signed-in users from guest users within Amazon CloudWatch RUM"](https://aws.amazon.com/blogs/mt/how-to-isolate-signed-in-users-from-guest-users-within-amazon-cloudwatch-rum/) that discusses this topic.

I'm closing this issue because it's in the domain of fraud prevention, which doesn't fall within the scope of this repository. Because this question is related to the CloudWatch RUM service itself, I recommend going through AWS support channels for more information.
